### ISSUE TITLE
uptime fails for systems where --pretty not supported

### ISSUE THREAD

**Issue by nathhad** [wick3dr0se/fetch.sh#12]
This would include smaller systems that are busybox based, for example.

[Example of failure case](http://www.aturnofthenut.com/wp-content/uploads/2021/11/fetch-OpenWRT21021.png)

Proposed fix: test for support of --pretty, present an answer based on plain uptime formatting if flag not supported.

(This is one I might tackle if I get a chance this week, since I have lots of busybox systems to test on.)

**Comment by wick3dr0se** [comment]
Upon merge of PR #20 this issue is fixed

**Comment by nathhad** [comment]
Confirmed fixed by pull request #20 and working (tested in place). Thanks!

**Comment by wick3dr0se** [comment]
commit 9eeaba1d08c4e15abe233971702d15fdc9381a43 changes if statement to read for uptime --pretty command instead. Thank you for the great work!

**Comment by nathhad** [comment]
commit 9eeeaba1 reverted the fix - `command -v uptime --pretty` does not successfully verify support for --pretty on busybox. So far the only thing I've found that clearly works is testing whether calling the command in question symlinks back to /bin/busybox.

**Comment by wick3dr0se** [comment]
I reopened the issue. Hoping we can find a way to print 'uptime' on busybox without path refrence to os

**Comment by nathhad** [comment]
Got it. One option, since there seem to have been other small systems that don't have the full version of `uptime --pretty` would be to just pull the raw uptime value (first field in /proc/uptime) and reformat it ourselves. That method is guaranteed to work the same on every Linux based system I've ever seen myself, and it's actually easier to process that value (which is just uptime in raw seconds) than trying to strip it out of the output of any of the uptime commands. Should only take a dozen lines of code, I don't have fetch handy to work directly but here is a code snippet you can use to extract, then format however you'd like:

```bash
#!/bin/bash
# Get raw seconds value
RAWSEC=$(cat /proc/uptime | awk '{print $1}')
# Cut off decimal
RAWSEC=${RAWSEC%\.*}
echo $RAWSEC
# Extract weeks
WEEKS=$((RAWSEC/604800))
REMSEC=$((RAWSEC%604800))
echo "$WEEKS weeks and $REMSEC seconds"
# Extract days
DAYS=$((REMSEC/86400))
REMSEC=$((REMSEC%86400))
echo "$WEEKS weeks, $DAYS days and $REMSEC seconds"
# Extract hours
HOURS=$((REMSEC/3600))
REMSEC=$((REMSEC%3600))
echo "$WEEKS weeks, $DAYS days, $HOURS hours and $REMSEC seconds"
# Extract minutes
MINUTES=$((REMSEC/60))
REMSEC=$((REMSEC%60))
echo "$WEEKS weeks, $DAYS days, $HOURS hours, $MINUTES min and $REMSEC seconds"
# format it however you like
echo "Compare to output of uptime --pretty:"
uptime --pretty
```

That produces the following terminal output:
```bash
chuck@vapor:~/code$ ./uptime.sh
5972231
9 weeks and 529031 seconds
9 weeks, 6 days and 10631 seconds
9 weeks, 6 days, 2 hours and 3431 seconds
9 weeks, 6 days, 2 hours, 57 min and 11 seconds
Compare to output of uptime --pretty:
up 9 weeks, 6 days, 2 hours, 57 minutes
```

Once you strip out my comments, you can use that to extract a time pattern that works on any system, even the tiny ones like Alpine and OpenWRT, no doubts.

**Comment by wick3dr0se** [comment]
Check out commit de093b496b5f446d735d53995d9cf587bf1e10a4
