### ISSUE TITLE
User display fails on systems where whoami not supported

### ISSUE THREAD

**Issue by nathhad** [wick3dr0se/fetch.sh#13]
This would include smaller systems that are busybox based, for example.

[Example of failure case](http://www.aturnofthenut.com/wp-content/uploads/2021/11/fetch-OpenWRT21021.png)

Proposed fix: test for presence of /usr/bin/whoami, and extract the username from /usr/bin/id instead if whoami not present on system.

(This is one I might tackle if I get a chance this week, since I have lots of busybox systems to test on.)

**Comment by wick3dr0se** [comment]
/usr/bin/id is a mess of nothingness for me. I tried to grep my username and searched through, couldn't find it. I think echo $USER could be possible fix?

**Comment by nathhad** [comment]
Got it, must be another difference in distros - but `echo $USER` definitely works cleanly on both Debian and OpenWRT/busybox for me, plus has the advantage of no further processing required. `id` tends to spit out your numeric uid, user name, and all your group info too, so I'd definitely take the shell variable as the first option instead!

**Comment by wick3dr0se** [comment]
Great, I'll switch it to the shell variable now! Thanks

**Comment by wick3dr0se** [comment]
commit 426726aefacb7c16ffe1deed78c3b533bae8265e fixed this
