### ISSUE TITLE
ram display fails on alternate (simplified) shells

### ISSUE THREAD

**Issue by nathhad** [wick3dr0se/fetch.sh#14]
This would include smaller systems that are busybox/ash based, for example.

[Example of failure case](http://www.aturnofthenut.com/wp-content/uploads/2021/11/fetch-OpenWRT21021.png)

Proposed fix: while this script is primarily meant for bash-based environments, this is one of the only parts of the script that fails under a simplified shell like ash. This one error would be very easily fixed by using POSIX arithmetic instead of bash let. Link: https://mywiki.wooledge.org/ArithmeticExpression

Fix would be to replace this line:

```bash
let "swap_mb = $swap_kb / 1024"
```

with this:

```bash
swap_mb=$(( $swap_kb / 1024 ))
```

(This is one I might tackle if I get a chance this week, since I have lots of busybox systems to test on.)

**Comment by nathhad** [comment]
This is now displaying properly - I believe one of the other commits knocked this one out as well. Closing now as fixed, thanks!

**Comment by wick3dr0se** [comment]
It was an improper whitespace issue. Good to see it's fixed!
