### ISSUE TITLE
Broken theme

### ISSUE THREAD

**Issue by egmose** [wick3dr0se/fetch.sh#16]
recent ARCH installation with gnome
Theme produces error message

tpe@tpe-002.odense.trustbox.local
kernel ~ 5.15.2-arch1-1
uptime ~ 1 day, 3 hours, 22 minutes
os ~ Arch Linux arch ~ x86_64
de/wm ~ GNOME-Classic;GNOME;GNOMEGNOME theme ~ grep: /home/tpe/.config/gtk-3.0/settings.ini: No such file or directory
cpu ~ Intel(R) Core(TM) i7-2670QM CPU @ 2.20GHz3.1@2.82GHz
gpu ~ Intel Corporation 2nd Generation Core Processor Family Integrated Graphics Controller (rev 09)
GF119M Quadro NVS 4200M (rev a1)
pkgs ~ 1016
ram ~ 7833 MiB swap ~ 8191 MiB
term ~ bash shell ~ bash

**Comment by wick3dr0se** [comment]
Closing this issue as commit e41c3c223a6c2ebeaab7c578f8cfb6c0847e7569 should have fixed this
