### ISSUE TITLE
DE/WM/Theme detection on minimal installs.

### ISSUE THREAD

**Issue by wimb0** [wick3dr0se/fetch.sh#17]
![image](https://user-images.githubusercontent.com/11030068/142908742-c1123b86-acce-4936-9b82-dfdb972b9b6a.png)

When running on my server, I get errors with DE/WM/Theme detection.
This is because there is no DE installed.
Maybe add logic to ignore these in the output when no DE is detected?

(Also, Max CPU speed is shown twice (and missing a space), and the sub GHz current speed misses the leading zero.)

**Comment by wick3dr0se** [comment]
I just made a couple commits that should fix your issues, can you check now?

**Comment by wimb0** [comment]
That was quick :-)
Seems to be solved!
![image](https://user-images.githubusercontent.com/11030068/142911920-4cf359b9-6233-4667-b57e-47db76686195.png)

No clue what 'Adwaita' is though...

**Comment by wick3dr0se** [comment]
Unfortunately Intel CPU's seem to include GHz. Not sure how to approach that just yet. I will keep this open as i'm working on closing the other issues. I'll probably just hide de/wm if not found, I need to remove the ' around theme name and hide 'Corporation' from gpu section

**Comment by wimb0** [comment]
For the GHz issue with Intel CPU's, maybe do something with if `vendor_id = GenuineIntel` in /proc/cpuinfo, do not add @1.23Ghz? (I'm not that good with shell scripts to fix that for you)

**Comment by wick3dr0se** [comment]
I pushed a new branch to intelcpu. Can you git clone -b intelcpu --single-branch https://github.com/wick3dr0se/fetch.sh and try this script? I dont want to push it to master until I know it works right

**Comment by wimb0** [comment]
Result of intelcpu.sh:
![image](https://user-images.githubusercontent.com/11030068/142920671-4a056691-d3e0-4457-b35c-00fd1f7cb4ca.png)

**Comment by wick3dr0se** [comment]
I approached it all wrong. Can you try it now?

**Comment by wimb0** [comment]
Done: result is now
![image](https://user-images.githubusercontent.com/11030068/142937237-b4980107-d3ed-43df-8472-a987aade9776.png)

**Comment by wick3dr0se** [comment]
That's what I like to see!

I just pushed commit 0da184b733f6e3eea198ea66c1270ed24f32e609 for intel systems to cleanup gpu output and of course fix the duplicate cpu speed issue on the master branch. If any issue appears just open new issue
