### ISSUE TITLE
Display installed package count on OpenWRT

### ISSUE THREAD

**Issue by nathhad** [wick3dr0se/fetch.sh#19]
OpenWRT uses opkg as the package tool. The quickest way to get installed package count here is:

```bash
opkg list-installed | wc -w
```

Thanks!

**Comment by wick3dr0se** [comment]
I'll add that now! Thank you for the command. You are much welcome to submit a PR with changes if you want to. I really appreciate you helping me clear all these issues!

**Comment by nathhad** [comment]
Very welcome! I needed a few minutes break from real work, so am working #12 right now - getting a nice-ish looking uptime for systems that don't support --pretty.

**Comment by wick3dr0se** [comment]
I just added the package manager for OpenWRT, should work! Awesome, I'm stumped on that one currently so trying to close the others

**Comment by nathhad** [comment]
As a follow up confirmation, this has been working perfectly since commit. Thanks!
