### ISSUE TITLE
Recommendation: Include load averages

### ISSUE THREAD

**Issue by nathhad** [wick3dr0se/fetch.sh#21]
Generally provided by uptime (though could use a lot of formatting to match the rest of the output here).

Not used by a lot of desktop users, but very useful for embedded systems, routers, and servers.

Most useful if paired with a core count on the CPU somewhere.

**Comment by wick3dr0se** [comment]
This is high priority on the roadmap. Really looking to add RAM & SWAP usage/total, CPU & GPU temps and replace uptime --pretty all together. My cpu outputs with the cores so we may have to figure something out using the $vendor variable or similar.

**Comment by saintphaenixos** [comment]
I've written a basic implementation that should cover this scenario. No core count as of yet in my implementation however.
