### ISSUE TITLE
ash on OpenWRT: CPU model read fails (pi 3B)

### ISSUE THREAD

**Issue by nathhad** [wick3dr0se/fetch.sh#23]
Attempt to read CPU info produces the following erroneous output:

```bash
ash: GenuineIntel: unknown operand
```

**Comment by wick3dr0se** [comment]
commit 397e7cdf61f95cbfb0fecff3d5f61c3c46427360 changes the operand at $vendor = GenuineIntel

**Comment by wick3dr0se** [comment]
commit accd4917288616e29dcd32e454fe0b0a7da6387b should remedy

**Comment by wick3dr0se** [comment]
closing per #28
