### ISSUE TITLE
gtk theme and de/wm not working

### ISSUE THREAD

**Issue by th4tkh13m** [wick3dr0se/fetch.sh#3]
I'm using DWM and a vanilla gtk theme and get the following result
```
th4tkh13m@myarch
kernel ~ 5.10.80-1-lts
uptime ~ 3 minutes
os ~ Arch Linux arch ~ x86_64
 theme ~ cpu ~ Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz@.900 GHz
gpu ~ Intel Corporation WhiskeyLake-U GT2 UHD Graphics 620 (rev 02)
pkgs ~ 487
ram ~ 15816 MiB swap ~ 4095 MiB
term ~ st shell ~ bash
```
Reason:
- I have no xsession folder
- I have no gtk theme in the ~/.config/gtk-3.0 folder

Solution:
- How about using `gsettings get org.gnome.desktop.interface gtk-theme` to find user's theme? It does work for me (showed `Adwaita`).

**Comment by wick3dr0se** [comment]
We can wrap this in an if, else statement to execute if command if found. I will work on this in the morning or feel free to submit another PR! I learned a lot from your last one

**Comment by wick3dr0se** [comment]
We can wrap this in an if, else statement to execute if command is found. I will work on this in the morning, you're welcome to submit a PR if you think of a way!
