### ISSUE TITLE
Issue with more than one swap again

### ISSUE THREAD

**Issue by jobbautista9** [wick3dr0se/fetch.sh#30]
Almost the same as #4. I can confirm that #11 fixed #4, but some commit after that seemed to have broken it again.

Output:

    job@job-pc
    kernel ~ 5.10.0-9-amd64
    uptime ~ 44 minutes
    os ~ Devuan GNU/Linux 4 (chimaera) arch ~ x86_64
    de/wm ~ XFCE theme ~ Breeze
    cpu ~ Intel Core i3-6006U   2.00GHz2.0@1.93GHz
    gpu ~ Intel  Skylake GT2 HD Graphics 520 (rev 07)
    pkgs ~ 4317
    ram ~ 3830 MiB./fetch.sh: line 141: let: swap_mb = 5242876
    12582908 / 1024: syntax error in expression (error token is "12582908 / 1024")
     swap ~ 5242876 MiB
    term ~ utmp shell ~ bash

EDIT: Seems to have been caused by df4d0c2.

**Comment by wick3dr0se** [comment]
Commit cfd04f7c9166ccc45fa1621c31fb95dac86dad8a attempts to resolve this issue. Confirmed working on Arch Linux with 2 swaps, for more swaps I will add them manually as requested. II don't think we can output too many swaps unless it ends up being highly sought after, then we can drop swap line down to it's own line of output

**Comment by jobbautista9** [comment]
Can confirm as well that it's fixed on my Devuan with 2 swaps, thanks!
