### ISSUE TITLE
DE/WM themes not working again

### ISSUE THREAD

**Issue by th4tkh13m** [wick3dr0se/fetch.sh#32]
Output 
```
th4tkh13m@myarch
kernel ~ 5.10.81-1-lts
uptime ~ 33 minutes
os ~ Arch Linux arch ~ x86_64
de/wm ~  theme ~ cpu ~ Intel Core i5-8365U   1.60GHz1.30@.8GHz
gpu ~ Intel  WhiskeyLake-U GT2 UHD Graphics 620 (rev 02)
pkgs ~ 492
ram ~ 15816 MiB swap ~ 4095 MiB
term ~ st shell ~ bash
```
Since I did not set GTK theme using `settings.ini` but using `gsettings set org.gnome.desktop.interface gtk-theme Theme`, it does not show up the theme. 
About the de/wm, your edited version did not work for me (printed nothing).

Also, I do think we must handle the case where the user uses the script in a tty (no DE/WM) by using an if/else statement:
```
if [ -z "${DISPLAY}" ]
then
    echo "none"
else
    output de/wm
fi
```

**Comment by wick3dr0se** [comment]
Can you verify the output of:

grep 'gtk-theme-name' ~/.config/gtk-3.0/settings.ini | sed 's/gtk-theme-name=//g' | sed 's/-/ /g'

I want to know if gtk-theme-name exist in the file in the first place for people that don't set it there or if it prints blank. I verified test -e works by changing path to '~/.config/gtk-3.0/settings.in and then my theme prints as Adwaita from gsettings. So, once I know the output of that command I can fix your issue by setting if that variable is set run command or similar

**Comment by th4tkh13m** [comment]
It prints nothing. And here is my settings.ini
```
[Settings]
gtk-application-prefer-dark-theme = true
```
I personally place the themes inside of ~/.themes and use a command (which is given in the comment above) to set themes.

**Comment by SaintFenix** [comment]
Sorry to say I'm getting the issue in a new form:

![image](https://user-images.githubusercontent.com/29680981/143154633-da1f05e7-a4aa-4fbc-a93c-fdcbf56cce79.png)
