### ISSUE TITLE
de/wm not detected correctly (xsessions)

### ISSUE THREAD

**Issue by jobbautista9** [wick3dr0se/fetch.sh#39]
Latest version (666fa88) now tells me I'm using Weston, but I'm not. I'm using XFCE. Some commit must've broken it...

    job@job-pc
    kernel ~ 5.10.0-9-amd64
    uptime ~ 0 weeks, 23 hours, 42 minutes
    os ~ Devuan GNU/Linux 4 (chimaera) arch ~ x86_64
    de/wm ~ Weston theme ~ Breeze
    cpu ~ Intel Core i3-6006U   2.00GHz2.00@2.0GHz
    gpu ~ Intel  Skylake GT2 HD Graphics 520 (rev 07)
    pkgs ~ 4317
    ram ~ 3830 MiB swap ~ 5119MiB 12287MiB
    term ~ utmp shell ~ bash

Might be caused by  433c555, as there's no `/usr/share/xsession` in my system.

**Comment by wick3dr0se** [comment]
Sorry for the typo. I don't think anyone has that directory. It was failing on my machine too; I just didn't notice because all of the de/wm options print 'i3' for me. Commit 6faf4ee06a1da791ac3dba67201d28b540dfc9e2 should be good to go

**Comment by jobbautista9** [comment]
Thanks. It no longer shows as Weston, but it still doesn't detect XFCE (nor its window manager xfwm4 either).

    job@job-pc
    kernel ~ 5.10.0-9-amd64
    uptime ~ 0 weeks, 25 hours, 45 minutes
    os ~ Devuan GNU/Linux 4 (chimaera) arch ~ x86_64
    de/wm ~  theme ~ Breeze
    cpu ~ Intel Core i3-6006U   2.00GHz2.00@.5GHz
    gpu ~ Intel  Skylake GT2 HD Graphics 520 (rev 07)
    pkgs ~ 4317
    ram ~ 3830 MiB swap ~ 5119MiB 12287MiB
    term ~ utmp shell ~ bash

**Comment by wick3dr0se** [comment]
How do you set your theme on your system? I need to know where theme variable exist

**Comment by wick3dr0se** [comment]
Can you run each one of these commands and share output of each in the same order? Make sure to use latest build from alpha branch

`head /usr/share/xsessions/* | grep -im1 'names=' | sed 's/DesktopNames=//'`

`head /usr/share/wayland-sessions/* | grep -im1 'name=' | sed 's/name=//gi' | sort -u | sed ':a;N;$!ba;s/\n/, /gi'`

`xprop -root | grep -m1 '^_NET_WM_NAME' | sed 's/^_NET_WM_NAME//g;s/(UTF8_STRING) = //g'`

**Comment by jobbautista9** [comment]
First and third command returns nothing for me. Second command returns `Weston`.

Output of latest alpha:

    job@job-pc
    kernel ~ 5.10.0-9-amd64
    uptime ~ 1 days, 22 hours, 56 minutes
    os ~ Devuan GNU/Linux 4 (chimaera) arch ~ x86_64
    de/wm ~  theme ~ Breeze
    cpu ~ Intel Core i3-6006U   2.00GHz2.0@.55GHz
    gpu ~ Intel  Skylake GT2 HD Graphics 520 (rev 07)
    pkgs ~ 4317
    ram ~ 3830 MiB swap ~ 5119MiB 12287MiB
    term ~ utmp shell ~ bash

**Comment by wick3dr0se** [comment]
Those are the 3 places I know to look off hand. How do you set your theme? Do you have xsettings command?

**Comment by wick3dr0se** [comment]
Those are the ones I have included in the script to look for your desktop environment currently.

Maybe your system has the environment variable set since it's a DE, try these:
`echo $XDG_CURRENT_DESKTOP`
`echo $DESKTOP_SESSION`

We could use the very commonly pre-installed dependency wmctrl, which was the single dependency I required with first commit, try:
`wmctrl -m`

Possible alternative could be:
`ps -e | grep "xfce"`
and filter output

**Comment by jobbautista9** [comment]
`echo $XDG_CURRENT_DESKTOP` = `XFCE`
`echo $DESKTOP_SESSION` = `lightdm-xsession`

I didn't have `wmctrl` installed. Installed it, and `wmctrl -m` returns:

    Name: Xfwm4
    Class: xfwm4
    PID: 3669
    Window manager's "showing the desktop" mode: N/A

`ps -e | grep "xfce"`:

     3500 ?        00:00:27 xfce4-session
     4754 ?        00:04:27 xfce4-panel
     4837 ?        00:00:05 xfce4-power-man
     4843 ?        00:00:04 xfce4-notifyd
    22600 ?        00:00:09 xfce4-settings-
    23188 ?        00:00:02 xfce4-appearanc

**Comment by wick3dr0se** [comment]
Check commit 0bdfb0e should fix by looking for $XDG_CURRENT_DESKTOP first

**Comment by jobbautista9** [comment]
It works now, thanks!
