### ISSUE TITLE
Doesn't work well in systems with more than one swaps

### ISSUE THREAD

**Issue by jobbautista9** [wick3dr0se/fetch.sh#4]
Script at line 88 assumes that the system don't have more than one swap. My system has two: one for zram and another as backup in hard disk.

https://github.com/wick3dr0se/fetch.sh/blob/ad6967c568381e9f52a33d0b8bb021c394994fd8/fetch.sh#L88

Example output:

    job@job-pc
    kernel ~ 5.10.0-9-amd64
    uptime ~ 5 days, 3 hours, 15 minutes
    os ~ Devuan GNU/Linux 4 (chimaera) arch ~ x86_64
    de/wm ~ XFCE theme ~ grep: /home/job/.config/gtk-3.0/assets: Is a directory
    /home/job/.config/gtk 3.0/settings.ini:Breeze
    cpu ~ Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz@2.000 GHz
    gpu ~ Intel Corporation Skylake GT2 HD Graphics 520 (rev 07)
    pkgs ~ 4317
    ram ~ 3830 MiB./fetch.sh: line 88: let: swap_mb = 5242876
    12582908 / 1024: syntax error in expression (error token is "12582908 / 1024")
     swap ~ 5242876 MiB
    term ~ utmp shell ~ bash

Will file the gtk dir problem in a separate issue.

**Comment by wick3dr0se** [comment]
I will hide this and stat other directories in the morning. As for the swap issue. I will think of a way to properly print as many as found in /proc/swaps. As per issue #5 , I will look in to whats causing the syntax failure. Feel free to submit a PR if you get any ideas in the meantime and thanks a ton for the info

**Comment by IndrekHaav** [comment]
Similar issue when there is no swap:

```
ram ~ 3793 MiB./fetch.sh: line 88: let: swap_mb =  / 1024: syntax error: operand expected (error token is "/ 1024")
```

**Comment by emilbratt** [comment]
Did a pull request that takes on this issue among some other stuff
 
Fix for multiple swap partitions, see bullet point 3
Fix for no spwa partitions, see bullet point 5

https://github.com/wick3dr0se/fetch.sh/pull/11

**Comment by wick3dr0se** [comment]
PR #11 merged and all issues appear to be resolved. If any remain, open new issue
