### ISSUE TITLE
Uptime display supposed to be like this?:

### ISSUE THREAD

**Issue by saintphaenixos** [wick3dr0se/fetch.sh#46]
So With the current build, and my computer I'm using that has an extended uptime, I'm getting a strange output in the Weeks and hours it's been on. (I know it's long, it'll be restarted shortly.)

I'm unsure if the intention of the output is to show weeks on, and then total hours on. or if it's supposed to be subracted from the previous values.

Here is that output:
![image](https://user-images.githubusercontent.com/25014799/143310837-79679a0b-f6fe-4e71-b6e3-828af2783f0d.png)

**Comment by wick3dr0se** [comment]
Definitely a bug, not intended. Commit 4c83a1f should fix

Pull latest commit from alpha branch; it should also fix the : appearing in de/wm there

**Comment by saintphaenixos** [comment]
This looks more sane, the semicolon in de/wm is gone:

![image](https://user-images.githubusercontent.com/25014799/143325299-5e9eebef-cca2-4b52-8689-2a8dcc06a19a.png)

However my uptime isn't right now, here is the result of my uptime command currently:

`16:30:01 up 41 days,  2:46,  1 user,  load average: 1.52, 2.11, 1.96`

give or take a few minutes in-between me typing up this reply.

**Comment by wick3dr0se** [comment]
I'm not sure whats causing that but the script can't manipulate your regular uptime command. Just stat time with fetch.sh instead. Closing as solved!
