### ISSUE TITLE
~/.config/gtk-3.0/assets: Is a directory

### ISSUE THREAD

**Issue by jobbautista9** [wick3dr0se/fetch.sh#5]
As mentioned in issue #4, I also encountered another problem when I ran the script.

Output:

    job@job-pc
    kernel ~ 5.10.0-9-amd64
    uptime ~ 5 days, 3 hours, 15 minutes
    os ~ Devuan GNU/Linux 4 (chimaera) arch ~ x86_64
    de/wm ~ XFCE theme ~ grep: /home/job/.config/gtk-3.0/assets: Is a directory
    /home/job/.config/gtk 3.0/settings.ini:Breeze
    cpu ~ Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz@2.000 GHz
    gpu ~ Intel Corporation Skylake GT2 HD Graphics 520 (rev 07)
    pkgs ~ 4317
    ram ~ 3830 MiB./fetch.sh: line 88: let: swap_mb = 5242876
    12582908 / 1024: syntax error in expression (error token is "12582908 / 1024")
     swap ~ 5242876 MiB
    term ~ utmp shell ~ bash

**Comment by Wasps0** [comment]
Getting this too with a Manjaro KDE install. Exact same line word for word but in french.

**Comment by wick3dr0se** [comment]
Closing this issue with the assumption that commit 01249ca40bebe0cc2e1be9ecf721d9137c511ef7 fixed the issue. If any persist open new issue

**Comment by Wasps0** [comment]
it's fixed for me
