### ISSUE TITLE
CPU Frequency issue under WSL2:

### ISSUE THREAD

**Issue by SaintFenix** [wick3dr0se/fetch.sh#53]
Opening a new issue about this:

![image](https://user-images.githubusercontent.com/29680981/143891557-7151c910-093a-41a1-be3c-4ffc7176aefc.png)

I'm beginning to think that a simple check to see if the file exists, and then not outputting anything may be the best way to go forward with this on WSL2, as there is no easy way to get the current CPU Frequency through WSL2.

I do wonder if this shows on other OS's under WSL2, also as I'm running Ubuntu only under WSL2.

**Comment by wick3dr0se** [comment]
These output errors should be resolved now but if you can find a path to get your cpu speed please do share it! Otherwise the latest build should just hide your cpu frequency

**Comment by SaintFenix** [comment]
Here's what we look like now:

![image](https://user-images.githubusercontent.com/29680981/144078957-477c08eb-ec52-4e3a-ba7f-e3619f6ac670.png)

I think for now this is perfect. I'll go ahead and keep some side work going into finding out how to read cpu speed on the WSL2 side, but think this should be the right direction for now.

@wick3dr0se thank you!

**Comment by wick3dr0se** [comment]
You should show terminal now too. Love being able to help but also broaden compatibility for our project at the same time. Thank you @SaintFenix!
