### ISSUE TITLE
lsblk: /dev/nvme0n1p: not a block device

### ISSUE THREAD

**Issue by juliavdkris** [wick3dr0se/fetch.sh#72]
Caused by this line, which strips the last character off a disk path if it's a number:
```bash
disk_path=${disk_path%[0-9]}
```

Which works fine for paths like `/dev/sda1`, but not if you have 10 or more partitions (because `/dev/sda10` would be cut to `/dev/sda1`). Or in my case, if you're using an NVME drive, because it cuts `/dev/nvme0n1p1` to `/dev/nvmen0n1p` instead of `/dev/nvmen0n1`

&nbsp;

To be honest, I don't really know a good way to fix this without adding a dependency like `lshw`. As far as I know, there's no easy way to differentiate between a device file and a partition file?

One dumb solution I just thought of was using lsblk, and filtering the block devices that are the "root" of their tree:
```bash
lsblk -ni | grep '^\w' | awk '{print $1}'
```

**Comment by wick3dr0se** [comment]
Thank you!! This outputs as 'sda' for me which is actually perfect. We could use this but another tester reported it output 3 seperate lines with 'sda' 'sdb' 'sdc' on their own lines. We could pipe it into `head -n1` or `sed -n 1p`. I'm not too sure how to properly handle this yet, we may need to move this to testing till we find a universal method

**Comment by wick3dr0se** [comment]
`df | grep -w '/' | awk '{print $1}'` does this output more than 1 result for you?

**Comment by juliavdkris** [comment]
> We could use this but another tester reported it output 3 seperate lines with 'sda' 'sdb' 'sdc' on their own lines

Yep, this would list all disk devices

> Does this output more than 1 result for you?

Nope that outputs just a single result, `/dev/nvme0n1p2`. But that would probably be more of a pain to try and cut to just the device name

**Comment by wick3dr0se** [comment]
Ok if that works as expected consistently than we can pipe it into 1 of those to just output the main drive each time? I'm hoping the current drive would always be listed first in lsblk. You're definitely right about that lol

**Comment by wick3dr0se** [comment]
`lsblk | awk -F ' ' 'FNR==2 {print $1}'` try this please

**Comment by juliavdkris** [comment]
> I'm hoping the current drive would always be listed first in lsblk

Nope, unfortunately not

> try this please

That outputs `/dev/sda`, which is my Windows drive :p

**Comment by juliavdkris** [comment]
One alternative for cutting partition paths to drive paths could be a regex? [Something like this](https://regexr.com/6bs64)

**Comment by wick3dr0se** [comment]
Then we can't make the former or the latter work correctly. I'm not sure why the drive you're using currently wouldn't output as the first result in lsblk. The second line should be your main drive and then a tree of the partitions in that drive and then inactive drives following below

That's actually a really cool website, thanks! It explains which each part does, so cool

**Comment by juliavdkris** [comment]
It seems to sort by device number by default (but can be changed with the `-x` flag). I had another idea of just grepping for which partition is mounted to `/`, but that wouldn't work if you have multiple mountpoints, like I do because of my Docker install

```
NAME        MAJ:MIN RM   SIZE RO TYPE MOUNTPOINTS
sda           8:0    0 931,5G  0 disk 
└─sda1        8:1    0 931,5G  0 part /run/media/julia/HDD
sdb           8:16   0 232,9G  0 disk 
├─sdb1        8:17   0   529M  0 part 
├─sdb2        8:18   0   100M  0 part 
├─sdb3        8:19   0    16M  0 part 
└─sdb4        8:20   0 232,3G  0 part /run/media/julia/70BE71E8BE71A6EE
nvme0n1     259:0    0 931,5G  0 disk 
├─nvme0n1p1 259:1    0     1G  0 part /efi
└─nvme0n1p2 259:2    0 930,5G  0 part /var/lib/docker/btrfs
                                      /
```

**Comment by wick3dr0se** [comment]
I can't figure out how to use the -x flag properly but maybe this? `lsblk -ln | grep -w '[0-9]:0' | awk '{print $1}'` better yet `lsblk -ln | awk '/:0/ {print $1}'`

**Comment by juliavdkris** [comment]
Ohhhh nice one! That prints `sda` and `nvme0n1` for me. But that means it wouldn't work if `sdb` was my root partition, as it the same major number as `sda`, and thus a non-zero minor number :/

**Comment by wick3dr0se** [comment]
I think the :0 status indicates that the drive is mounted somewhere currently but I could be wrong. That's my hope lol

**Comment by juliavdkris** [comment]
I think it has to do with different disk types, `sda` and `sdb` are SCSI devicecs, `nvme0n1` is an NVME device.

On the bright side: I just found a cool thing! You can just do `findmnt /` to find the partition that is mounted at `/`. It's part of the `util-linux` package, so pretty much built in on any Arch install

So to get the root partition path: `findmnt -n / | awk '{print $2}'`, and then throw that in the regex I posted earlier :)

**Comment by wick3dr0se** [comment]
Cool! That's shorter syntax than df but I'm not sure if df or findmnt are more commonly installed on most systems. This is the same method and output as df

**Comment by juliavdkris** [comment]
`df` is part of coreutils, `findmnt` is part of util-linux. Both are part of the base package group, so you can assume they will be installed on practically every Arch system. And `findmnt` is more reliable, since it will always list the root partition and doesn't have the minor device number issue with `sda` and `sdb` that I mentioned earlier

**Comment by wick3dr0se** [comment]
I'm worried about other systems mostly. I want to ensure Arch compatibility first but I want to make sure each distro works. Findmnt prints /dev/sda3 for me just like df does but I do prefer the findmnt method if it's widely available. I think this is a good method for sure but may throw a script in testing and just merge it when it's tested on other systems. I was very weary about adding it in the first place. I know a lot of people are going to have very long disk outputs and we have to strip on a case by case basis like we do with cpu and gpu

**Comment by juliavdkris** [comment]
I assume pretty much every distro (except maybe for Alpine) will have util-linux as part of the base install

**Comment by juliavdkris** [comment]
I checked some Docker images, and Ubuntu and Debian have it installed by default, Alpine as expected doesn't (but if you're using Alpine you'd probably install these tools yourself). Interestingly enough though, Fedora and OpenSUSE don't have it either. Though I suspect the actual installs will have it by default, but the Docker image is just minimized.

**Comment by wick3dr0se** [comment]
Thank you for checking on that. I think that df is definitely the more common option. It's installed with Termux but findmnt isn't. I ran the regex in sed and it doesn't output anything for me. I'm not really sure how re-create the right regex. I'm going to remove the code for now and push a seperate script to testing

**Comment by juliavdkris** [comment]
I just did some quick tests in virtual machines, and like I thought OpenSUSE and Fedora (and even NixOS!) actually do have `findmnt` by default as well. The only one that doesn't have it by default as far as I know is Alpine, but that doesn't have `lsblk` either lmao

**Comment by juliavdkris** [comment]
And I would argue that if compatibility is what you're going for, having multiple drives (which breaks with the `lsblk -ln | awk '/:0/ {print $1}'` thing) is much more common than a Linux install that doesn't have `util-linux` :p

**Comment by wick3dr0se** [comment]
We would just do FNR==1 to print the first line and it would still work but I'm not sure I'd be able to come up with a decent regex any time soon. I still have some learning to do to make a regex like that and properly understand it

**Comment by juliavdkris** [comment]
Sure, but like I said the first line isn't guaranteed to be the root partition

**Comment by wick3dr0se** [comment]
Yea, we would have to stick with the original method then. It can be a bit cleaner, like `df / | awk 'FNR==2 {print $1}'` and then use a regex strip like the one you suggested

**Comment by wick3dr0se** [comment]
I was thinking about this more.. I still don't know a way to make a regex like the one you made but we could do something like `[[ $disk_model = *"nvme"* ]] && disk_model=${disk_model%1p}` if all nvme drives end with path like 1p on the end. We could built onto this if there is few differences

**Comment by juliavdkris** [comment]
The `n1` in `nvme0n1p1` indicates the first NVME drive, so it's not guaranteed to be 1. But the regex I sent earlier matches either `/dev/sd{any letter}` or `/dev/nvme{any number}n{any number}`. I think just grepping for that regex and outputting the first match group would be the easiest.

I have actually made a small change that allows it to detect devices with counters longer than one char (like `/dev/nvme11n22p1` or `/dev/sdaaa`): https://regexr.com/6c047

**Comment by juliavdkris** [comment]
Here's a grep command that searches this regex and outputs the full device path:
```bash
grep -Eo '/dev/(?nvme[0-9]+n[0-9]+|sd[a-z]+)'
```

![image](https://user-images.githubusercontent.com/22723225/146933270-85ce3af0-c3f5-4a94-ae3c-f7f9a9be89af.png)

The Arch wiki actually has a nice thing that explains device path naming conventions: https://wiki.archlinux.org/title/Device_file#Block_device_names

**Comment by wick3dr0se** [comment]
Thanks! With your help and that amazing link to the ArchWiki, I was able to come up with a solution. I filled a text file with the block device paths below then just wrapped it in a while loop conditional. This worked for stripping all of these properly. In case someone boots from SD mmcblk will strip; I'm not sure about vda or sr. I don't think loop is a possible mounting path but I threw it in anyway. Commit 562e9e9495075ca8edf000a5bcd0cf787045271b should fix this issue

/dev/sda1 > /dev/sda
/dev/sdc10 > /dev/sdc
/dev/nvme2n5p3 > /dev/nvme2n5
/dev/mmcblk3p4 > /dev/mmcblk3
/dev/vda1 > /dev/vda
/dev/loop0p2 > /dev/loop0
/dev/sr02 > /dev/sr0

**Comment by juliavdkris** [comment]
Yesss that works here, nice job!

**Comment by wick3dr0se** [comment]
@juliavdkris Great, thanks! Wouldn't have been possible without you!
