### ISSUE TITLE
Arch WSL2 output very slim

### ISSUE THREAD

**Issue by Miepee** [wick3dr0se/fetch.sh#74]
```
$ bash sysfetch
kernel ~ 5.10.16.3-microsoft-standard-WSL2  arch ~ x86_64
```

1) isn't there supposed to be shown more?
2) according to the screenshot on the homepage, architecture and kernel should not be on the same line.

**Comment by wick3dr0se** [comment]
Much more should be there but the WSL script is way out of date. I will update what I can. I'll have to setup a Windows VM to write some code. There was a contributor handling the WSL portion of sysfetch for a bit

I just moved architecture up to that line to tighten things up a bit. I plan to add more features like temperatures

**Comment by wick3dr0se** [comment]
Closing this issue due to dropping support for WSL. I intend to maintain this for Linux only from now on!
