### ISSUE TITLE
Errors on Android via Termux

### ISSUE THREAD

**Issue by Miepee** [wick3dr0se/fetch.sh#75]
This is run via Termux
There are errors about `/etc/os-release`, `/etc/lib/os-release` (both for getting OS name probably), `/etc/issue`, `lspci` (likely related to #7), `/sys/devices/virtual/dmi/id/board_vendor` and `/sys/devices/virtual/dmi/id/board_name` (both for getting mobo).

In addition, the CPU is also missing its name.
![image](https://user-images.githubusercontent.com/38186597/169765169-f9cd66e4-a481-4b1a-b500-3eb4fb655777.png)

**Comment by Miepee** [comment]
CPU missing its name seems to be a similar cause to #8, considering my phone is also ARM based.

**Comment by wick3dr0se** [comment]
There are some Android specific commands that should be able to pull things like CPU but I have a lot to learn there. I will keep this up as a feature. I think right now operating system priority should be like:

1. Linux
2. BSD
3. Mac
4. WSL
5. Android

I may be wrong. The good part is Android runs the Linux kernel so several commands work already. My main focus is to get Linux completely stable before adding more. If any contributors want to work on any specific script in the meantime, they can assume credibility!

**Comment by Miepee** [comment]
From that priority list, Windows via MINGW / MSYS seems unsupported?

**Comment by wick3dr0se** [comment]
Termux or other BusyBox systems don't include typical Linux coreutils ans therefore won't have consistent behavior. Instead of comforming to all these variables; I have decided to drop support for Termux (Android), similarly to WSL
