### ISSUE TITLE
Not able to access drive and exiting on Alpine

### ISSUE THREAD

**Issue by Miepee** [wick3dr0se/fetch.sh#76]
```
# bash sysfetch
sysfetch: line 7: /dev/fd/62: No such file or directory
@
```

Worth noting that this was run on an emulated Linux machine in the browser: <https://bellard.org/jslinux/>

Also worth noting: `uname -snrmo` (which is in Line 7) does execute fine: `Linux localhost 4.12.0-rc6-g48ec1f0-dirty i586 Linux`

**Comment by wick3dr0se** [comment]
Your documentation and effort is tremendous.. It means a lot. I will see if I can reproduce this error and find a possible fix

**Comment by wick3dr0se** [comment]
Alpine is a BusyBox system and doesn't come installed with GNU coreutils. We can't cater to all the variables across systems so the focus is on Linux only in the future!
