### ISSUE TITLE
No output on Fedora VM

### ISSUE THREAD

**Issue by Miepee** [wick3dr0se/fetch.sh#77]
Was testing in a Fedora 36 VM, for some reason the script just freezes/gets in an endless loop and does not output anything.
The issue in particular seems to be line 4, as commenting that out makes the script actually progress:
https://github.com/wick3dr0se/sysfetch/blob/96e09ca58021067c47c5d77b700d35a6cf710317/sysfetch#L4

**Comment by Miepee** [comment]
Someone on reddit also seemed to have the same but on Arch via `sysfetch-git` from AUR:
https://old.reddit.com/r/linux/comments/uvdkrb/comment/i9o0l3k/?utm_source=share&utm_medium=web2x&context=3

**Comment by wick3dr0se** [comment]
I'm not sure what is causing this *bug* of sorts. I used the same line in the last release and it worked great. I really need to figure this one out. For some reason it works with sudo apparently but nothing happens when ran without elevation

**Comment by wick3dr0se** [comment]
This may fixed now. Make sure to not run sysfetch command from inside the script directory. Trying to find a way to solve that issue as well

**Comment by wick3dr0se** [comment]
This issue should surely be solved now. If anyone can report back from Fedora; Please let me know!
