### ISSUE TITLE
Verbose option

### ISSUE THREAD

**Issue by Miepee** [wick3dr0se/fetch.sh#79]
Having a verbose option which would list whether some parameters were found or not would be nice.

**Comment by wick3dr0se** [comment]
This is a realllly good idea! I will work on implementing this ASAP! Maybe just throw errors if verbose, if not hide errors

**Comment by Miepee** [comment]
Not sure what you mean by "throw"; if you mean that program execution would be halted, I'd disagree.
If you mean to print the errors somewhere, then that's what I had in mind.

**Comment by wick3dr0se** [comment]
Well typically you say a program throws errors when it literally writes errors. So that is what I was referring to. 

That's exactly what I meant. If --verbose, then 'spit out' errors to the terminal; No flag, hide errors.

**Comment by wick3dr0se** [comment]
I added a statement that sends all errors to /dev/null if verbose flag is not supplied

**Comment by Miepee** [comment]
> Well typically you say a program throws errors

May depend on the language, when I hear throwing, i think of this:
https://en.wikipedia.org/wiki/Exception_handling#Syntax
